remote_theme: pmarsceill/just-the-docs
title: Projects of TH Latypov
description: Projects and demos
base: "/supplemental"
url: "https://latypovt.github.io/"

include: ['_pages', 'RD_QR_slide', 'OHBM_Conv', 'IASP2022_MM', 'Neuronto']
